### ISSUE TITLE
support for webpack 3?

### ISSUE THREAD

**Issue by dmecke** [iampava/imagemin-webp-webpack-plugin#12]
After adding the plugin and restarting the webpack-dev-server it crashes with the message

```
[project_directory]\node_modules\webpack-dev-server\bin\webpack-dev-server.js:387
		throw e;
		^

TypeError: Cannot read property 'emit' of undefined
    at ImageminWebpWebpackPlugin.apply ([project_directory]\node_modules\imagemin-webp-webpack-plugin\plugin.js:26:24)
    at Compiler.apply ([project_directory]\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack ([project_directory]\node_modules\webpack\lib\webpack.js:32:19)
    at startDevServer ([project_directory]\node_modules\webpack-dev-server\bin\webpack-dev-server.js:381:14)
    at processOptions ([project_directory]\node_modules\webpack-dev-server\bin\webpack-dev-server.js:364:3)
    at Object.<anonymous> ([project_directory]\node_modules\webpack-dev-server\bin\webpack-dev-server.js:496:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

I am using webpack 3, is this supported?

**Comment by iampava** [comment]
Hey! Unfortunately no, just webpack 4. But I will update the README to specify this
